### ISSUE TITLE
Batchfile "activate.bat" not found when installing/executing SESMG

### ISSUE THREAD

**Issue by DV-Bongingi** [SESMG/SESMG#181]
Hi @jtock,
I downloaded v0.5.0 and installed python, graphviz and cbc according to the installation manual. 
When trying to run SESMG I receive the error message "activate.bat" not found. Reading the "Run_SESMG_for_windows.cmd" batchfile tells me, the programm is looking for the directory "cd Scripts/start /b activate.bat", but in the downloaded structure of SESMG-ZIP folder, there is no such folder named "Scripts" on the level of the commandfile. 
Can you give me advise, how to solve the issue? 
(by the way: in the older version 0.2.0 the folder "Scripts" does exist at the described directory)
Greetings

**Comment by chrklemm** [comment]
@DV-Bongingi please try to restart the installation from scartch in a completely new folder. The error message indicates, that there was a problem during the implementation of the virtual environment, in which the SESMG is installed. Make sure, that you only reference two digits of your python version (e.g., "3.8" instead of "3.8.3") when starting the installation file.

**Comment by jtock** [comment]
We added some notes to the documentation in commit f5b905f .
