### ISSUE TITLE
activate.bat file

### ISSUE THREAD

**Issue by LeaSchwei** [SESMG/SESMG#191]
Hej, when I try to run SESMG, after following the installation guide, I have a message about activate.bat which cannot be found. Did I do something wrong or is there a solution please ?

![image](https://github.com/SESMG/SESMG/assets/138015485/5b479a04-38aa-41e0-8d10-bad140ee2907)

**Comment by chrklemm** [comment]
Hi @LeaSchwei!
Great, that you are using the SESMG! Could you please provide the following information?

- What SESMG version are you using?
- What Python version are you using?
- Have you followed the entire installation procedure described in the documentation? https://spreadsheet-energy-system-model-generator.readthedocs.io/en/latest/02.01.00_installation.html#windows

It seems that you are trying to install the SESMG in a folder which is synchronized with OneDrive - that caused a comparable problem in the past. I would recommend to reinstall the SESMG from scratch in a folder which is not synchronized with OneDrive.

Best regards,
@chrklemm

**Comment by LeaSchwei** [comment]
Hej @chrklemm,

Thanks for the answer!

I am using Python 3.11 and the master version of SESMG.

I reinstalled Python and it is ok now but I have the error "no module named streamlit" even when I follow exactly the installation mode and the advice on this web page https://spreadsheet-energy-system-model-generator.readthedocs.io/en/latest/03.00.00_trouble_shooting.html.

![image](https://github.com/SESMG/SESMG/assets/138015485/f694e7bb-c4e1-41e9-a59f-d2e8f396c09c)

**Comment by jtock** [comment]
Hi @LeaSchwei,

the SESMG is not compatible with all Python versions so far. We support Python 3.7, 3.8 and 3.9. Since you are using Python 3.11 the installation is not running properly. 

You can install a second Python version on your machine which is aiming the SESMGs requirements. I recommend to use Python 3.9.13 which is widely tested.

Feel free to contact is again if you have any problems! If you are facing problems or challenges while using the SESMG you can use our discussion section on GitHub which you will find here: https://github.com/SESMG/SESMG/discussions

Greeting 
Jan

**Comment by jtock** [comment]
Addendum: You need to run the installation process again from scratch in a new folder / new environment when installing with a new Python version.

**Comment by jtock** [comment]
@LeaSchwei I hope we were able to help you! Please reopen this / another issue or use the discussion section if you have further questions. 
Greetings Jan
