### ISSUE TITLE
solar thermal collector

### ISSUE THREAD

**Issue by janik257** [SESMG/SESMG#96]
Invest cap. is multiplied with the conversion factor (create objects lines 205 to 207) so we multiply the invest (m2) with the peridical costs (€/kW).
@YannickWittor are we right?

In order to fix, we delete the factors in the lines mentioned above and changed the create results,
lines 212 to 217 (new):
            #if comp_type == 'source':
                #if comp['input'] not in [0, 'None', 'none']:
                    # considers area conversion factor on investment for
                    # solar heat sources
                    #component_investment = \
                        #component_investment / comp['Conversion Factor']

If we are right, we have to change the prints of the solarthermal collectors (_Max Heat power output per year and m²: 0.00 kWh/(m²a), Irradiance on collector per year and m²: 0.29 kWh/(m²a)_)

**Comment by YannickWittor** [comment]
Yes, you are right. There ist a problem. 

About your solution: I think you have to consider the other result parameters aswell. They also have to be divided by/multiplied with the conversion factor. Otherwise e.g. the results for annual energy output would be lower, because the function calculates kWh on the basis of m² and to a solar thermal system applies m²>kW (kW = scenario input).

So far for further discussion, maybe I am missing something or one of you have another idea how to implement this.

**Comment by GregorBecker** [comment]
Is it correct that the error has been fixed in the dev_open_district_upscaling branch ? @janik257

**Comment by janik257** [comment]
check if costs are condisidered right in standard parameter sheet
